name: CI

on: [ push, pull_request ]

jobs:

  build:
    uses: ./.github/workflows/run-npm.yml
    with:
      npm-script: build

  test:
    uses: ./.github/workflows/run-npm.yml
    with:
      npm-script: test

  check:
    uses: ./.github/workflows/run-npm.yml
    with:
      npm-script: check

  build-doc:
    uses: ./.github/workflows/run-npm.yml
    with:
      npm-script: doc

  doc:
    runs-on: ubuntu-latest
    needs: build-doc
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install elm-doc
      - name: Generate docs
        run: elm-doc . --output docs --fake-license 'SPDX license name'

  # publish:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Elm Publish
  #       uses: dillonkearns/elm-publish-action@v1
  #       with:
  #         github-token: ${{ secrets.GITHUB_TOKEN }}
  #         path-to-elm: ./node_modules/.bin/elm
  #     - run: npm run build
  #     - id: npm-publish
  #       if: github.ref == 'refs/heads/main'
  #       uses: JS-DevTools/npm-publish@v1
  #       with:
  #         token: ${{ secrets.NPM_TOKEN }}
